### ISSUE TITLE
Approximate sync callback is always one full period stale

### ISSUE THREAD

**Issue by lucasw** [fkie/message_filters#2]
I was trying out comparing fkie_message_filters approx sync to regular message_filters in https://github.com/lucasw/ros_example/tree/main/ros_example/src and they both trigger the callback 1 full time period late if there is a time offset- if I publish two messages with a slight time offset in header stamps at 1 Hz the callback is a full second behind when the two messages were published.

```
rosrun ros_example sync_pub _offset:=0.001
rosrun ros_example fkie_message_filters_sync
```

If I zero out the header stamp time difference the callback is completely up to date to about a millisecond, which is the same as with using exact sync:

```
rosrun ros_example sync_pub _offset:=0.0
```

```
rosrun ros_example fkie_message_filters_sync _exact:=true
```

I tried `set_max_age()` to less than the update period but then the callback is never called, it receives the pair of messages and then sits on them until the time runs out then discards them?

Could there be a easy fix for this, perhaps optional (was there a desire to wait as long as possible just in case a better synchronized message arrives?), where if two messages are buffered and they are less than the set_max_timespan() time_delta and say 2 * time_delta has expired then go ahead and trigger the callback?  Or maybe that already exists and I missed it.

**Comment by lucasw** [comment]
I didn't have the right search term, putting 'delay' in led me to https://answers.ros.org/question/289922/approximate-time-sync-callback-delay-issue/

**Comment by roehling** [comment]
You probably want to set [set_min_distance()](https://fkie.github.io/message_filters/classfkie__message__filters_1_1combiner__policies_1_1ApproximateTime.html#a71f3206ec9ad49ff5d67dbc52a901c2d):
> If it is known in advance that messages from a certain source cannot arrive closer together than min_dist, the policy can conclude earlier that a set of matched messages is optimal, thereby reducing the introduced lag. A typical example would be a camera with fixed frame rate F, where the minimum distance between consecutive messages can be assumed to be at least 0.5/F.

**Comment by lucasw** [comment]
Yeah that works https://github.com/lucasw/ros_example/commit/94374493d95e70f3a4c4871516bd4114f3591e71

I think there is an oddity still with setting a negative time offset on one of the sync messages, the sync callback is triggered slower than if there is a positive offset

```
./sync_pub.py _offset:=-0.0001
```

But it's small enough it doesn't matter too much, or maybe it's worth looking into more later.
